### ISSUE TITLE
ISSUE: As a fan I should be able to Delete my account? 

### ISSUE THREAD

**Issue by ILikeConcerts** [CrouchJumpInc/fangagement-public#26] opened 2022-03-10 07:18 UTC
I create the account "Carl" just to test the account deletion process. I get the pop-up that states "Are you sure you want to delete your account?" I write DELETE in the comment area as instructed in the pop-up instructions and then go to click the red delete button but it doesn't work. It registers my touch but it just stays in pop-up mode until I cancel the process.

"Existence is Pain" Carl states.

**Comment by DrVonDevious** [comment] 2022-03-11 03:37
closing as a duplicate of #5

**Closed** 2022-03-29 20:09 UTC
