### ISSUE TITLE
ISSUE: As a fan I should be able to change my Password? 

### ISSUE THREAD

**Issue by ILikeConcerts** [CrouchJumpInc/fangagement-public#25] opened 2022-03-10 07:09 UTC
Clicked on "Change" for my password in the profile settings. A pop-up appeared to notify me to check my email. Never received an email.

**Comment by DrVonDevious** [comment] 2022-03-11 03:39
closing as a duplicate of #5

**Closed by DrVonDevious** 2022-03-11 03:39 UTC
